/**
 * Bundle of img-about
 * Generated: 2018-12-27
 * Version: 1.2.0
 * License: MIT
 * Author: livelybone(2631541504@qq.com)
 */

!function(e,t){"object"==typeof exports&&"undefined"!=typeof module?t(exports):"function"==typeof define&&define.amd?define(["exports"],t):t(e.ImgAbout={})}(this,function(e){"use strict";function n(r){return new Promise(function(e,t){var n=document.createElement("img"),o=function(){e({width:n.width,height:n.height})};n.onload=o,n.onerror=function(){t(new Error("Image loaded error"))},n.src=r,n.complete&&o()})}function r(t){return new Promise(function(e){"string"==typeof t?e(n(t)):t.naturalWidth?e({width:t.naturalWidth,height:t.naturalHeight}):e(n(t.src))})}"undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self&&self;var t,f=(function(e){var t;t=function(){return function(e,t,n){t=t||"",n=n||512;for(var o=atob(e),r=[],i=0;i<o.length;i+=n){for(var a=o.slice(i,i+n),c=new Array(a.length),s=0;s<a.length;s++)c[s]=a.charCodeAt(s);var d=new Uint8Array(c);r.push(d)}return new Blob(r,{type:t})}},e.exports?(e.exports=t(),e.exports.default=e.exports):window.b64toBlob=t()}(t={exports:{}},t.exports),t.exports);e.getNaturalSize=r,e.imgMinify=function(e,t){if(!document.createElement("canvas").getContext)return Promise.reject(new Error("Canvas is not supported in your browser"));var o,u=["scale","fixedWidth","fixedHeight","fixedSize"],n={compressType:"scale",scale:1,width:0,height:0,size:0,quality:.8,toBlob:!0},l=n;return t&&Object.keys(n).forEach(function(e){l[e]=void 0!==t[e]?t[e]:n[e]}),(o=e,new Promise(function(t,n){try{var e=new FileReader;e.onload=function(e){t(e.target.result)},e.readAsDataURL(o)}catch(e){n(e)}})).then(function(c){var s=document.createElement("canvas"),d=s.getContext("2d");return r(c).then(function(e){var t,n,o=e.width,r=e.height;l.compressType===u[1]?(t=l.width,n=l.width*r/o):l.compressType===u[2]?(n=l.height,t=l.height*o/r):l.compressType===u[3]?r<o?(n=l.size,t=l.size*o/r):(t=l.size,n=l.size*r/o):(t=o*l.scale,n=r*l.scale),s.width=t,s.height=n;var i=document.createElement("img");i.src=c,d.drawImage(i,0,0,t,n);var a=s.toDataURL("image/jpeg",l.quality);return l.toBlob?function(e){try{var t=e.split(","),n=t[0].match(/:(.*?);/)[1];return Promise.resolve(f(t[1],n))}catch(e){return Promise.reject(e)}}(a):a})})},e.imageCopy=function(e){var t;return e instanceof Image?t=e:"string"==typeof e&&((t=new Image).src=e),Promise.resolve().then(function(){document.body.appendChild(t),function(e,t){var n,o=Object.assign({},t,{clearSelect:!1,cut:!1}),r=o.clearSelect,i=o.cut;if(window.getSelection){var a=window.getSelection();n=window.document.createRange(),a.removeAllRanges(),n.selectNode(e),a.addRange(n)}else document.body.createTextRange&&((n=document.body.createTextRange()).moveToElementText(e),n.select());window.document.execCommand("copy");r&&a.removeAllRanges(),i&&(e.value="")}(t)})},Object.defineProperty(e,"__esModule",{value:!0})});
